version: '3.7'

services:
  ai-quiz-postgres:
    image: postgres:15
    container_name: ai-quiz-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ai-quiz-pgdata:/var/lib/postgresql/data

volumes:
  ai-quiz-pgdata:
