name: Docker Hub Push & EC2에 개발용 컨테이너 띄우기

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: 빌드 작업
    runs-on: ubuntu-latest

    env:
      # 프로젝트
      PROJECT_NAME: ai-rena-backend
      ENV_CONTENT: ${{ secrets.DEVELOP_ENV_CONTENT }}
      # Docker
      DOCKER_ID: ${{ secrets.DOCKER_ID }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: .env 등록
        run: echo "${{ env.ENV_CONTENT }}" > .env

      - name: Docker Hub에 로그인
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_ID }}" --password-stdin

      - name: Docker 이미지 빌드
        run: docker build -t ${{ env.DOCKER_ID }}/${{ env.PROJECT_NAME }}:develop .

      - name: Docker 이미지 푸시
        run: |
          docker push ${{ env.DOCKER_ID }}/${{ env.PROJECT_NAME }}:develop

  deploy:
    name: 개발 서버 배포 작업
    needs: build
    runs-on: ubuntu-latest

    env:
      # 프로젝트
      PROJECT_NAME: ai-rena-backend
      # AWS
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
      # Dokcer
      DOCKER_ID: ${{ secrets.DOCKER_ID }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: EC2에 배포
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          debug: true
          script: |
            echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_ID }}" --password-stdin
            docker pull ${{ env.DOCKER_ID }}/${{ env.PROJECT_NAME }}:develop
            docker stop ${{ env.PROJECT_NAME }}-develop || true
            docker rm ${{ env.PROJECT_NAME }}-develop || true
            docker run -d --name ${{ env.PROJECT_NAME }}-develop -p 3001:3000 ${{ env.DOCKER_ID }}/${{ env.PROJECT_NAME }}:develop
            docker image prune -af
