name: Production-Deploy-From-Github-Go-AWS-EC2-With-DockerHub
on:
  push:
    branches: ['SUS-71-cd-setup']
  pull_request:
    branches: ['SUS-71-cd-setup']
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_ID}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_ID }}-${{ secrets.PROJECT_NAME }}:latest \
                      -t ${{ secrets.DOCKER_ID }}-${{ secrets.PROJECT_NAME }}:${{ github.run_id }} .

      - name: DockerHub Push
        run: |
          docker push ${{secrets.DOCKER_ID}}/${{secrets.PROJECT_NAME}}:latest
          docker push ${{secrets.DOCKER_ID}}/${{secrets.PROJECT_NAME}}:${{github.run_id}}

      - name: Application Build and Run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{secrets.EC2_KEY}}
          script: |
            sudo docker kill ${{secrets.PROJECT_NAME}}
            sudo docker rm -f ${{secrets.PROJECT_NAME }}
            sudo docker rmi ${{secrets.DOCKER_ID}}/${{secrets.PROJECT_NAME}}
            sudo docker pull ${{secrets.DOCKER_ID}}/${{secrets.PROJECT_NAME}}
            sudo docker run -p ${{secrets.AWS_EC2_PORT}}:${{secrets.AWS_EC2_PORT}} \
            --name ${{secrets.PROJECT_NAME}} \ 
            -d ${{secrets.DOCKER_ID}}/${{secrets.PROJECT_NAME}}
