name: Production-Deploy-From-Github-Go-AWS-EC2-With-DockerHub
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Docker Image Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_ID}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_ID }}/${{ secrets.PROJECT_NAME }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{secrets.DOCKER_ID}}/${{secrets.PROJECT_NAME}}:latest
  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Application Build and Run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER}}
          key: ${{secrets.EC2_KEY}}
          script: |
            docker stop ${{secrets.PROJECT_NAME}}
            docker rm -f ${{secrets.PROJECT_NAME }}
            docker rmi ${{secrets.DOCKER_ID}}/${{secrets.PROJECT_NAME}}
            docker pull ${{secrets.DOCKER_ID}}/${{secrets.PROJECT_NAME}}
            docker run -p ${{secrets.EC2_PORT}}:${{secrets.EC2_PORT}} --name ${{secrets.PROJECT_NAME}} -d ${{secrets.DOCKER_ID}}/${{secrets.PROJECT_NAME}}
            docker image prune -af
